#ifndef __APP_CFG_H
#define __APP_CFG_H

//TASK PRIORITIES
#define APP_TASK_START_PRIO			2
#define	APP_TASK_RELAYS1_PRIO		3
#define APP_TASK_RELAYS2_PRIO		3

//TASK STACK SIZES
#define APP_TASK_START_STK_SIZE		128
#define APP_TASK_RELAYS1_STK_SIZE 	512
#define APP_TASK_RELAYS2_STK_SIZE 	512

#endif
